calibrate_params.Rmd:
  path: dev/calibrate_params.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/calibrate-simulation-parameters.Rmd
  inflate:
    flat_file: dev/calibrate_params.Rmd
    vignette_name: Calibrate simulation parameters
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_first.Rmd:
  path: dev/flat_first.Rmd
  state: active
  R:
  - R/formatting_data.R
  - R/calibrate_params_phenotypes.R
  - R/compute_beta_g.R
  - R/compute_beta_matrix_cluster.R
  - R/compute_current_microbiome.R
  - R/compute_mean_microbiome.R
  - R/compute_phenotypes.R
  - R/gen_effect_calibration.R
  - R/generate_founder.R
  - R/get_mean_diversity.R
  - R/get_mean_phenotypes.R
  - R/get_microbiomes.R
  - R/get_om_beta_g.R
  - R/get_phenotypes.R
  - R/get_phenotypes_value.R
  - R/get_selected_ind.R
  - R/holo_simu.R
  - R/rarefied_microbiome.R
  - R/read_input_data.R
  - R/root.R
  - R/select_individual.R
  - R/transform_geno_into_vcf.R
  - R/deru.R
  tests: tests/testthat/test-formatting_data.R
  vignettes: []
  inflate:
    flat_file: dev/flat_first.Rmd
    vignette_name: ~
    open_vignette: true
    check: true
    document: false
    overwrite: ask
    clean: ask
    codecov: false
generate-figures.Rmd:
  path: dev/generate-figures.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/generate-figures.Rmd
  inflate:
    flat_file: dev/generate-figures.Rmd
    vignette_name: Generate figures
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
import-data.Rmd:
  path: dev/import-data.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/import-data.Rmd
  inflate:
    flat_file: dev/import-data.Rmd
    vignette_name: Import Data
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
